In [1]:
import numpy as np
import pandas as pd

# data cleaning

In [2]:
df = pd.read_excel('trainset.xlsx')

In [3]:
df.head()

,Compound Identifier,Odor,Replicate,Intensity,Dilution,subject #,INTENSITY/STRENGTH,VALENCE/PLEASANTNESS,BAKERY,SWEET,...,ACID,WARM,MUSKY,SWEATY,AMMONIA/URINOUS,DECAYED,WOOD,GRASS,FLOWER,CHEMICAL
0,126,4-Hydroxybenzaldehyde,NaN,low,"1/1,000",1,7,62.0,0.0,0.0,...,0.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0
1,126,4-Hydroxybenzaldehyde,NaN,high,2019-01-10 00:00:00,1,37,60.0,0.0,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,126,4-Hydroxybenzaldehyde,NaN,low,"1/1,000",2,55,89.0,0.0,33.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3,126,4-Hydroxybenzaldehyde,NaN,high,2019-01-10 00:00:00,2,64,71.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
4,126,4-Hydroxybenzaldehyde,NaN,low,"1/1,000",3,89,68.0,0.0,62.0,...,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
trainy_m = df.groupby("Compound Identifier").mean()
trainy_s = df.groupby("Compound Identifier").std()
trainy_m = trainy_m.drop(trainy_m.columns[0], axis=1)
trainy_s = trainy_s.drop(trainy_s.columns[0], axis=1)

In [5]:
trainy_m.head()

,INTENSITY/STRENGTH,VALENCE/PLEASANTNESS,BAKERY,SWEET,FRUIT,FISH,GARLIC,SPICES,COLD,SOUR,...,ACID,WARM,MUSKY,SWEATY,AMMONIA/URINOUS,DECAYED,WOOD,GRASS,FLOWER,CHEMICAL
Compound Identifier,,,,,,,,,,,,,,,,,,,,,
126,37.102041,49.850000,0.537500,21.087500,7.050000,0.162500,2.000000,4.212500,4.987500,5.375000,...,4.300000,3.187500,7.137500,1.287500,2.750000,4.462500,0.825000,1.537500,7.487500,14.362500
176,8.051020,48.000000,1.785714,4.904762,1.047619,1.809524,5.809524,6.619048,3.595238,11.642857,...,3.071429,5.190476,6.976190,7.238095,3.785714,3.380952,2.809524,3.166667,4.714286,7.595238
177,22.387755,48.666667,8.257576,17.924242,2.651515,0.636364,1.045455,2.181818,6.242424,9.363636,...,3.439394,3.515152,5.181818,1.621212,2.333333,3.363636,0.651515,2.878788,3.469697,14.090909
196,14.530612,46.472727,1.254545,11.527273,0.763636,0.418182,3.909091,5.945455,4.254545,9.618182,...,6.290909,7.200000,8.418182,6.109091,1.800000,4.963636,1.000000,2.327273,5.600000,8.763636
239,24.683673,50.575758,1.196970,13.575758,3.863636,1.303030,3.984848,5.621212,4.363636,8.121212,...,2.848485,5.803030,6.318182,1.348485,0.818182,4.848485,4.257576,5.787879,8.909091,9.909091

In [6]:
trainy_s.head()

,INTENSITY/STRENGTH,VALENCE/PLEASANTNESS,BAKERY,SWEET,FRUIT,FISH,GARLIC,SPICES,COLD,SOUR,...,ACID,WARM,MUSKY,SWEATY,AMMONIA/URINOUS,DECAYED,WOOD,GRASS,FLOWER,CHEMICAL
Compound Identifier,,,,,,,,,,,,,,,,,,,,,
126,31.688070,23.124375,2.175489,29.484685,21.448142,1.344880,9.662665,13.140616,16.232873,13.357191,...,11.101830,11.563905,17.173533,5.923978,8.669019,15.844932,4.566734,6.268151,20.577113,22.281992
176,17.722589,22.980373,8.019901,13.659285,5.179473,11.727055,18.850164,18.740789,12.175665,24.369935,...,9.462101,14.017825,16.134327,19.524606,16.463612,13.643461,9.610051,9.543013,16.924921,21.428337
177,29.248185,23.763795,20.664582,29.263425,9.435599,3.475790,5.918502,8.333268,17.991503,21.888976,...,12.255145,10.878691,12.765228,6.978572,9.977410,12.535042,4.808622,12.598553,15.498109,28.284123
196,23.490820,24.224150,5.409930,22.463843,3.179586,3.101319,14.155581,16.884595,14.109648,21.757494,...,16.811232,19.036417,18.701051,19.080408,8.483972,15.574152,4.136558,9.510335,19.835061,18.027719
239,27.858848,23.683204,6.944217,23.379847,12.372285,7.501733,14.267222,12.720384,15.968851,20.691518,...,9.170593,13.649705,17.802471,5.939418,4.597354,18.792177,15.949257,17.342270,21.063806,22.152428

In [7]:
testset = pd.read_excel('testset.xlsx')
testy_m = testset.drop('sigma', axis = 1)
testy_s = testset.drop('value', axis = 1)
testy_m = testy_m.pivot(index='oID', columns = 'descriptor')
testy_m.columns = testy_m.columns.droplevel(0)
testy_s = testy_s.pivot(index='oID', columns = 'descriptor')
testy_s.columns = testy_s.columns.droplevel(0)

In [8]:
testy_m.head()

descriptor,CHEMICAL,ACID,AMMONIA/URINOUS,BAKERY,BURNT,COLD,DECAYED,FISH,FLOWER,FRUIT,...,GRASS,INTENSITY/STRENGTH,MUSKY,SOUR,SPICES,SWEATY,SWEET,VALENCE/PLEASANTNESS,WARM,WOOD
oID,,,,,,,,,,,,,,,,,,,,,
180,10.5000,3.2188,5.281200,3.37500,2.90620,7.6250,6.21880,2.281200,12.62500,6.468800,...,6.593800,16.714,7.5312,9.0312,4.3750,0.03125,15.5310,55.438,10.03100,8.625000
262,3.4706,2.3235,1.382400,14.17600,1.26470,2.1471,8.20590,3.529400,3.47060,5.235300,...,0.029412,36.816,10.4410,13.2650,1.2647,8.17650,19.6180,51.147,10.35300,0.029412
264,14.1630,6.5918,14.265000,0.55102,7.38780,1.1429,16.73500,4.163300,0.93878,0.061224,...,1.102000,86.980,20.4490,27.4080,4.3469,19.32700,1.1633,22.857,6.67350,4.571400
323,12.2860,3.4286,2.408200,19.49000,6.24490,6.3673,0.69388,0.020408,11.30600,11.020000,...,1.449000,59.163,1.6735,4.4694,8.7347,1.61220,32.8370,66.551,9.26530,1.653100
702,4.7083,1.3333,0.083333,7.83330,0.20833,3.2500,0.00000,0.000000,1.08330,0.041667,...,0.916670,10.612,6.1667,4.2917,9.5000,3.12500,26.8330,58.667,0.79167,0.333330

In [9]:
testy_s.head()

descriptor,CHEMICAL,ACID,AMMONIA/URINOUS,BAKERY,BURNT,COLD,DECAYED,FISH,FLOWER,FRUIT,...,GRASS,INTENSITY/STRENGTH,MUSKY,SOUR,SPICES,SWEATY,SWEET,VALENCE/PLEASANTNESS,WARM,WOOD
oID,,,,,,,,,,,,,,,,,,,,,
180,18.168,11.460,17.00500,13.3680,13.9250,20.705,18.3860,7.95650,25.8670,15.25100,...,19.2940,26.504,21.7060,19.415,14.393,0.17678,26.8000,23.997,20.6980,20.2970
262,13.230,11.159,7.88560,27.6650,7.1998,7.932,23.5090,17.35400,17.3030,19.12800,...,0.1715,33.934,21.8720,26.395,5.017,25.09800,29.2120,25.520,23.7000,0.1715
264,26.310,17.278,30.01400,2.7162,16.1070,6.045,28.0530,14.03000,5.5242,0.42857,...,7.7143,13.587,31.4680,36.707,12.797,31.36700,4.6339,28.100,18.6610,16.7000
323,23.974,10.805,9.65000,34.7510,17.3740,18.658,4.7135,0.14286,26.6510,25.44600,...,9.9980,30.851,6.9504,12.260,21.668,7.92360,33.1680,26.175,21.5540,11.4260
702,16.594,6.532,0.40825,22.2570,1.0206,14.501,0.0000,0.00000,5.3072,0.20412,...,3.7290,22.681,18.2030,15.429,24.996,14.68300,34.0020,22.588,3.0925,1.6330

In [10]:
molecular = pd.read_excel('molecular.xlsx',index_col='CID')

In [11]:
molecular.head()

,complexity from pubmed,MW,AMW,Sv,Se,Sp,Si,Mv,Me,Mp,...,Psychotic-80,Psychotic-50,Hypertens-80,Hypertens-50,Hypnotic-80,Hypnotic-50,Neoplastic-80,Neoplastic-50,Infective-80,Infective-50
CID,,,,,,,,,,,,,,,,,,,,,
126,93.1,122.13,8.142,10.010,15.305,10.193,16.664,0.667,1.020,0.680,...,0,0,0,0,0,0,0,0,0,0
176,31.0,60.06,7.508,4.483,8.422,4.432,9.249,0.560,1.053,0.554,...,0,0,0,0,0,0,0,0,0,0
177,10.3,44.06,6.294,3.768,7.095,3.977,8.040,0.538,1.014,0.568,...,0,0,0,0,0,0,0,0,0,0
180,26.3,58.09,5.809,5.295,9.978,5.739,11.455,0.530,0.998,0.574,...,0,0,0,0,0,0,0,0,0,0
196,114.0,146.16,7.308,11.493,20.727,11.625,22.914,0.575,1.036,0.581,...,0,0,0,0,0,0,0,0,0,0

In [12]:
trainx = molecular[molecular.index.isin(trainy_m.index.values)]
testx = molecular[molecular.index.isin(testy_m.index.values)]

In [13]:
testx.head()

,complexity from pubmed,MW,AMW,Sv,Se,Sp,Si,Mv,Me,Mp,...,Psychotic-80,Psychotic-50,Hypertens-80,Hypertens-50,Hypnotic-80,Hypnotic-50,Neoplastic-80,Neoplastic-50,Infective-80,Infective-50
CID,,,,,,,,,,,,,,,,,,,,,
180,26.3,58.09,5.809,5.295,9.978,5.739,11.455,0.530,0.998,0.574,...,0,0,0,0,0,0,0,0,0,0
262,30.5,90.14,5.634,8.064,16.073,8.716,18.495,0.504,1.005,0.545,...,0,0,0,0,0,0,0,0,0,0
264,49.5,88.12,6.294,7.537,14.189,7.955,16.080,0.538,1.014,0.568,...,0,0,0,0,0,0,0,0,0,0
323,196.0,146.15,8.597,12.010,17.305,12.193,18.664,0.706,1.018,0.717,...,0,0,0,0,0,0,0,0,0,0
702,2.8,46.08,5.120,4.295,8.978,4.739,10.455,0.477,0.998,0.527,...,0,0,0,0,0,0,0,0,0,0

In [14]:
trainx.head()

,complexity from pubmed,MW,AMW,Sv,Se,Sp,Si,Mv,Me,Mp,...,Psychotic-80,Psychotic-50,Hypertens-80,Hypertens-50,Hypnotic-80,Hypnotic-50,Neoplastic-80,Neoplastic-50,Infective-80,Infective-50
CID,,,,,,,,,,,,,,,,,,,,,
126,93.1,122.13,8.142,10.010,15.305,10.193,16.664,0.667,1.020,0.680,...,0,0,0,0,0,0,0,0,0,0
176,31.0,60.06,7.508,4.483,8.422,4.432,9.249,0.560,1.053,0.554,...,0,0,0,0,0,0,0,0,0,0
177,10.3,44.06,6.294,3.768,7.095,3.977,8.040,0.538,1.014,0.568,...,0,0,0,0,0,0,0,0,0,0
196,114.0,146.16,7.308,11.493,20.727,11.625,22.914,0.575,1.036,0.581,...,0,0,0,0,0,0,0,0,0,0
239,52.8,89.11,6.855,7.031,13.407,7.199,15.163,0.541,1.031,0.554,...,0,0,0,0,0,0,0,0,0,0

# variable

trainx: train x 

trainy_m : train y of mean

trainy_s : train y of std

testx : test x

testy_m : test y of mean

testy_s : test y of std

# analysis

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostRegressor